comment: true

coverage:
  status:
    project:
      default:
        target: auto    # must not decrease from base branch
        threshold: 0.01% # allow fluctuation
    patch:
      default:
        target: 0%      # minimum coverage for changed lines
