name: Codecov Upload

on:
  workflow_run:
    workflows:
      - Coverage Build
    types:
      - completed

permissions:
  contents: read
  actions: read
  pull-requests: read

jobs:
  upload-coverage:
    name: Upload Coverage
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # must download source code
        with:
          fetch-depth: 0

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: jacoco-coverage
          path: coverage
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
#          override_commit: ${{ steps.pr.outputs.sha }}
#          override_branch: ${{ steps.pr.outputs.branch }}
#          override_pr: ${{ steps.pr.outputs.number }}
          override_commit: ${{ github.event.pull_request.head.sha }}
          override_branch: ${{ github.event.pull_request.head.ref }}
          override_pr: ${{ github.event.pull_request.number }}
          fail_ci_if_error: true
          verbose: true
